### ISSUE TITLE
Got errors in "01_ocdc_dataloader.ipynb", could you release source codes of training from scratch and produce .pt files?

### ISSUE THREAD

**Issue by BenoitKAO** [dalifreire/tumor_regions_segmentation#8]
Thank you for your marvelous work.

I run 01_ocdc_dataloader.ipynb and got errors:
...
last_model_name = get_model_list(checkpoint_path, "gen", iteration=430000)
...
ValueError: Not found models with this iteration

Could you release source codes of training from scratch and produce .pt files?

Any help is appreciated.

**Comment by BenoitKAO** [comment]
Dear Mr. Dalí,

Sorry for my late reply since I have rebuilt the whole environment several times for running your source codes these days.
And if it is convenient for you, could you release your env file(like .yaml)?

From your previous reply, It works!

However, it is stuck again, and some errors are occured in "02_ocdc_train.ipynb"

First,
there is no "train_model(..." defined in "ocdc_train.py."
and I modified it with "train_model_with_validation(..." to run.

Second,
I have referenced from "02_orca_train.ipynb" to "02_ocdc_train.ipynb"
a. 
"csv_file_path = "{}/training_loss_random.csv".format(training_dir)"
ocdc and orca have both no "training_loss_random.csv" file

I use the generated 'ocdc_training_accuracy_loss.csv' for the replacement.

The errors are generated:
ParserError: Error tokenizing data. C error: Expected 7 fields in line 12002, saw 8

b.
I dounf the issue could be:
"valid = df[df['phase'] == 'valid']", which is Empty DataFrame.

c.
I found there is no column "valid" in 'ocdc_training_accuracy_loss.csv.'
Therefore, could you point out how to modify your source codes for creating column "valid" in "train_model_with_validation(..." and similar functions?

Thank you very much, and any help is appreciated.

**Comment by dalifreire** [comment]
@BenoitKAO,

OCDC dataset does not use a validation subset to train (uses train and test instead of train and validation).
I fixed the 02_ocdc_train notebook. Could you try to update your branch with the last commits?

It's not clear to me what exactly you are trying to do. Are you trying to train the model from the scratch using some new image datasets?

**Comment by BenoitKAO** [comment]
@dalifreire 
It is nice to have your reply.

A.
After updated your last commits, "02_ocdc_train.ipynb" is passed.
However, "referenced from "02_orca_train.ipynb" to "02_ocdc_train.ipynb" for the drawn diagrams by generated .csv file still does not work.

B.
It isn't evident: 
...
# loads our trained fcn model
trained_model_version = "XX"
...
Should it be put in the best performance .pth file?

C.
it is stuck again, and I cannot find any ".svs" file.
May I check with you where can I download the ".svs" files?
Like '1009011.svs' and so on,

D.
I want to go and run through your programs with every step.
Indeed, I would like to try to train the model from scratch using custom datasets?

Thank you very much.
Any help is appreciated.
